- hosts: server1
  vars:
    - app1: httpd
    - app2: vsftpd

  tasks:
    - name: install {{ app1 }} and {{ app2 }}
      yum:
        name:
          - "{{ app1 }}"
          - "{{ app2 }}"
        state: present
